### ISSUE TITLE
tesseract2.py

### ISSUE THREAD

**Issue by cicero34** [pymupdf/PyMuPDF-Utilities#31] opened 2022-01-03 06:09 UTC
First, thanks for implementing such a great package.  It is very helpful.

We are trying to run the tesseract2.py example code on the attached file and not getting any output.  From inspecting the variables, it seems that the line "blocks = page.get_text("dict", flags=0)["blocks"]" is not returning any object, suggesting to us that the problem lies in the interaction with tesseract.  We note that we are able to convert manually the attached file to txt using pdf2image and tesseract in the same environment.  

Our configuration is as follows:

$ echo $TESSDATA_PREFIX
/usr/share/tesseract-ocr/4.00/tessdata
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> print(fitz.__doc__)

PyMuPDF 1.19.4: Python bindings for the MuPDF 1.19.0 library.
Version date: 2022-01-01 00:00:01.
Built for Python 3.10 on linux (64-bit).
[microsoft_subscription_agrt.pdf](https://github.com/pymupdf/PyMuPDF-Utilities/files/7800596/microsoft_subscription_agrt.pdf)

**Comment by JorjMcKie** [comment] 2022-01-03 10:24
There is a misconception:
This a script that only invokes OCR if
1. the page does contain normal text
2. text contains illegible (single) characters

If either of the above is not true, no OCR function will be invoked.

But OCRing the file as such is possible:
```python
>>> import fitz
>>> doc = fitz.open("microsoft_subscription_agrt.pdf")
>>> page = doc[0]
>>> tp = page.get_textpage_ocr(dpi=300, full=True)
>>> print(page.get_text(textpage=tp))
Microsoft Online Subscription Agreement
Last updated: March 2019
Microsoft Online Subscription Agreement

>>> 
```

**Comment by cicero34** [comment] 2022-01-04 03:47
Got it!  Thanks for the quick and helpful reply.

**Comment by JorjMcKie** [comment] 2022-01-04 14:41
Assuming this has been answered ...

**Closed by JorjMcKie** 2022-01-04 14:41 UTC

**Comment by JorjMcKie** [comment] 2022-01-04 15:04
Another question that may come into your mind:
How am I supposed to know that a page is worthwhile OCRing?

In the case of your example page 0, the answer is relatively simple:
1. The page contains no "normal" text: `page.get_text() == ""`.
2. The page yet has a relatively large amount of `/Contents` data: `len(page.read_contents() = 124868`. **_Everything_** shown by the page is caused by "painting" instructions in this object type: normal text, display commands for images and basic drawings (like lines, rectangles, curves).

Because we have no text, but 124 KB of painting instructions, a lot of other stuff must be happening. An image invocation command only needs one or two handful of bytes, so we can assume the bulk of data on this page indeed is basic drawings.

In this situation, there is a fat chance we have a page with text existing in the form of drawings: each character is drawn using lines or curves - an "O" is drawn as an ellipse, a "d" is a right-open semi-circle followed by a "|" line, etc., etc.
The only way to extract this type of text is indeed OCRing the page.
